import {
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  FontColor,
  FontBackgroundColor,
  FontSize,
  FontFamily,
  Highlight,
  Link,
  List,
  BlockQuote,
  Table,
  TableToolbar,
  TableProperties,
  TableCellProperties,
  Image,
  ImageToolbar,
  ImageUpload,
  ImageCaption,
  ImageStyle,
  ImageInsert,
  ImageResize,
  CodeBlock,
  PasteFromOffice,
  RemoveFormat,
  HorizontalLine,
  Indent,
  IndentBlock,
  Base64UploadAdapter,
  Alignment,
  FindAndReplace,
  Autoformat,
  SpecialCharacters,
  SpecialCharactersEssentials,
} from "ckeditor5";

import "ckeditor5/ckeditor5.css";

export const editorConfig = {
  // Use empty string for standard open-source commercial bypass or "GPL" for open-source builds
  licenseKey: "GPL", 
  plugins: [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    FontColor,
    FontBackgroundColor,
    FontSize,
    FontFamily,
    Highlight,
    Link,
    List,
    BlockQuote,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    Image,
    ImageToolbar,
    ImageUpload,
    ImageCaption,
    ImageStyle,
    ImageInsert,
    ImageResize,
    CodeBlock,
    PasteFromOffice,
    RemoveFormat,
    HorizontalLine,
    Indent,
    IndentBlock,
    Base64UploadAdapter,
    Alignment,
    FindAndReplace,
    Autoformat,
    SpecialCharacters,
    SpecialCharactersEssentials,
  ],
  toolbar: [
    "heading",
    "|",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "subscript",
    "superscript",
    "removeFormat",
    "|",
    "fontFamily",
    "fontSize",
    "fontColor",
    "fontBackgroundColor",
    "highlight",
    "|",
    "link",
    "bulletedList",
    "numberedList",
    "alignment",
    "outdent",
    "indent",
    "|",
    "blockQuote",
    "codeBlock",
    "insertTable",
    "horizontalLine",
    "|",
    "imageUpload",
    "|",
    "findAndReplace",
    "specialCharacters",
    "|",
    "undo",
    "redo",
  ],
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
  image: {
    insert: { integrations: ["upload", "url"] },
    toolbar: ["imageStyle:full", "imageStyle:side", "|", "imageTextAlternative"],
  },
};